### ISSUE TITLE
Add web3 wallet integration

### ISSUE THREAD

**Issue by iemwill** [iemwill/hellow#4]
Example at https://docs.cloud.coinbase.com/wallet-sdk/docs/web3-react

**Comment by clairecharles** [comment]
Hey @iemwill I would love to work on this :)

**Comment by iemwill** [comment]
Hello @clairecharles that is very nice. I've just updated the README and if you're at step 3, let me know. Also before, if the installation process doesn't succeed.

It could be easier to just go with `window.ethereum` from https://web3js.readthedocs.io/en/v1.7.5/getting-started.html depending on how much walletproviders support that.

**Comment by iemwill** [comment]
Am questioning a bit if this is helpful or in general for that purpose wanted at all...

**Comment by clairecharles** [comment]
Hey, sorry i haven't made a pr yet. will do that today!
